const types = {
    SET_CURRENT_ADMIN_ORDERS: "SET_CURRENT_ADMIN_ORDERS",
    SET_CURRENT_ADMIN_NOTIFICATIONS: "SET_CURRENT_ADMIN_NOTIFICATIONS",
    CLEAR_ADMIN_DATA: "CLEAR_ADMIN_DATA"
};

export default types;
