const types = {
    SET_CATEGORIES: "SET_CATEGORIES",
    SET_CATEGORY_ITEMS: "SET_CATEGORY_ITEMS",
    SET_SEARCH_RESULTS: "SET_SEARCH_RESULTS",
    SET_SEARCH_STRING: "SET_SEARCH_STRING"
};

export default types;
